### ISSUE TITLE
Provider memory leak

### ISSUE THREAD

**Issue by grod220** [prax-wallet/web#121]
useEffect should return a removeEventListener as well as an abort here:

https://github.com/penumbra-zone/web/blob/f515113fac3b4e3a4d7a2561c20ac0f06d535abd/packages/react/src/components/penumbra-context-provider.tsx#L93

Separately, I'm not sure it makes sense to have an addEventListener for a single event `penumbrastate`. This feels like it could be a function that returns a cleanup function with a more constricted API.

**Comment by turbocrime** [comment]
the abort signal is provided to the `addEventListener` options parameter, which achieves removal of the listener. this is not a leak.

https://github.com/penumbra-zone/web/blob/f515113fac3b4e3a4d7a2561c20ac0f06d535abd/packages/react/src/components/penumbra-context-provider.tsx#L76-L93

**Comment by grod220** [comment]
Ah gotcha, didn't realize the abortController removes the listener 👍
