### ISSUE TITLE
Transaction confirmations are automatically canceled for plans with a lot of actions 

### ISSUE THREAD

**Issue by Valentine1898** [prax-wallet/web#130]
**Describe the bug**
Transactions are automatically canceled when trying to create a dutch auction spread over 48 auctions
In some cases this is not reproduced, but more often it is reproduced

**To Reproduce**

1. Go to Swap
2. Create dutch auction for 24 or 48 hours
3. You'll get a approval dialog and transaction cancellation after a couple of seconds

**Expected behavior**
Prax should be able to create transactions with any number of actions

**Screenshots**

https://github.com/user-attachments/assets/2d08dc5f-2a94-4389-a3bc-d02b8479f587

**Comment by grod220** [comment]
I can't seem to reproduce this. Do you see any errors in the console for minifront or prax?

**Comment by Valentine1898** [comment]
> I can't seem to reproduce this. Do you see any errors in the console for minifront or prax?

Yes, I'm getting these errors in prax

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/34fec1bc-1e39-461a-a459-b5a6386d23eb">

**Comment by TalDerei** [comment]
cc @jessepinho

**Comment by Valentine1898** [comment]
@grod220 
I've concluded that the issue here 
https://github.com/prax-wallet/web/blob/8141aa42264e9873bbb6f2c625bf12145bc10da6/apps/extension/src/popup.ts#L23
Increasing the timeout solves the issue, but we probably want to have a more flexible solution

**Comment by grod220** [comment]
Good find. This relates to this issue: https://github.com/penumbra-zone/web/issues/285. We should have a think about good designs for this.
