### ISSUE TITLE
Figure out how to ensure that icons render in the correct color

### ISSUE THREAD

**Issue by jessepinho** [prax-wallet/web#158]
They render with `currentColor`, but that will be changed once https://github.com/penumbra-zone/web/pull/1665 is merged, since that PR will no longer set all text to be `text.primary` color.

Should icons render as `text.primary` by default? Or just `currentColor`? If the latter, should we change the `<Icon />` component's `color` prop to accept a function that takes the `theme` as its argument, and returns e.g., `theme.color.someColor.main`?

**Comment by VanishMax** [comment]
Implemented in https://github.com/penumbra-zone/web/pull/1665
