### ISSUE TITLE
Onboarding will suddenly abort if you try to continue with custom rpc 

### ISSUE THREAD

**Issue by Valentine1898** [prax-wallet/web#69]
If you try to use custom RPC during the onboarding phase, a `chain-id` change warning window will be shown (which probably shouldn't have been shown). 
Most likely, this also sends a `СlearCache` message to the service worker, but the service worker is not initialized yet and this causes a crash  
<img width="800" alt="image" src="https://github.com/prax-wallet/web/assets/25391690/60d388fc-57be-4fad-964f-4040bb995526">

**Comment by grod220** [comment]
Good find. I think this slipped through as we've been typically entering in custom RPCs that serve the same chain id. 

However, there is an issue when there will be zero rpcs in the list. With `fixEmptyGrpcEndpointAfterOnboarding()`, there is a hardcoded testnet rpc there that prefills the input. We should delete this. But it also is subject to the bug you found (trying to go from testnet -> another chain... popup err).

**Comment by Valentine1898** [comment]
Aww, it's not that simple with `fixEmptyGrpcEndpointAfterOnboarding`. If we want to remove this logic, we need to consider that the user can interrupt onboarding at any time and come back to it later. In this case, if the user has not yet selected RPC, then we should not consider that his onboarding is complete
