### ISSUE TITLE
Tracking issue: Use remote npm versions of packages

### ISSUE THREAD

**Issue by grod220** [prax-wallet/web#8]
Currently errors when using the published npm versions of the following packages. See `package.json` for name on npm (e.g. `@penumbra-zone/zquery`)

===
(priority for skip integration)
- [x] #9
- [x] #10
- [x] #11
- [x] #12 

===
- [x] #13
- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] #18
- [x] #19
- [x] #20
- [x] #21
- [x] #22

These are currently not published:

- [x] #23
- [x] #24
- [x] #25
- [ ] #26

**Comment by VanishMax** [comment]
@grod220 Most of the packages are integrated, can we close them? The only ones left are zquery and ui

**Comment by TalDerei** [comment]
status of this tracking issue?
